export const GET_MESSAGE_START = 'GET_MESSAGE_START';
export const GET_MESSAGE_END = 'GET_MESSAGE_END';
export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS';
export const GET_MESSAGE_FAILURE = 'GET_MESSAGE_FAILURE';

export const CLEAR_DELETE_MESSAGE_STORE = 'CLEAR_DELETE_MESSAGE_STORE';
export const CLEAR_MESSAGE_STORE = 'CLEAR_MESSAGE_STORE';