export const CLEAR_USER_STORE = 'CLEAR_USER_STORE';

export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_END = 'CREATE_USER_END';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_END = 'LOGIN_USER_END';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
